anchors_:
  working_dir: &working_dir
    working_directory: ~/repo

  pull_cache: &pull_cache
    restore_cache:
      keys:
        - deps-{{ .Branch }}-{{ checksum "yarn.lock" }}-v1

  push_cache: &push_cache
    save_cache:
      paths:
        - node_modules
      key: deps-{{ .Branch }}-{{ checksum "yarn.lock" }}-v1

  install: &install
    run: yarn install --frozen-lockfile

  node8_image: &node8_image
    docker:
      - image: circleci/node:8.11.3

  node10_image: &node10_image
    docker:
      - image: circleci/node:10.7.0

  require_setup: &require_setup
    requires:
      - setup

version: 2
jobs:
  setup:
    <<: *node8_image
    <<: *working_dir
    steps:
      - checkout
      - <<: *pull_cache
      - <<: *install
      - <<: *push_cache

  node10:
    <<: *node10_image
    <<: *working_dir
    steps:
      - checkout
      - <<: *pull_cache
      - <<: *install
      - run: yarn test

  node8:
    <<: *node8_image
    <<: *working_dir
    steps:
      - checkout
      - <<: *pull_cache
      - <<: *install
      - run: yarn test

  lint:
    <<: *node8_image
    <<: *working_dir
    steps:
      - checkout
      - <<: *pull_cache
      - <<: *install
      - run: yarn lint

  coveralls:
    <<: *node8_image
    <<: *working_dir
    steps:
      - checkout
      - <<: *pull_cache
      - <<: *install
      - run: yarn coverage:post

workflows:
  version: 2
  build:
    jobs:
      - setup
      - node8:
          <<: *require_setup
      - node10:
          <<: *require_setup
      - lint:
          <<: *require_setup
      - coveralls:
          <<: *require_setup
