# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
commands:
  get_deps:
    parameters:
      node:
        type: integer
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-node<< parameters.node >>-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-node<< parameters.node >>-{{ checksum "package.json" }}
            - v1-dependencies-node<< parameters.node >>

  save_deps:
    parameters:
      node:
        type: integer
    steps:
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-node<< parameters.node >>-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}

  install_deps:
    steps:
      - run: npm ci

  run_test:
    steps:
      - run: npm run test

  run_lint:
    steps:
      - run: npm run lint

  setup_deps:
    parameters:
      node:
        type: integer
    steps:
      - get_deps:
          node: << parameters.node >>
      - install_deps
      - save_deps:
          node: << parameters.node >>

executors:
  node16:
    docker:
      - image: circleci/node:16.13
    working_directory: ~/repo

  node14:
    docker:
      - image: circleci/node:14.18
    working_directory: ~/repo

  node12:
    docker:
      - image: circleci/node:12.22
    working_directory: ~/repo

jobs:
  test_node16:
    executor: node16
    steps:
      - checkout
      - setup_deps:
          node: 16
      - run_test

  test_node14:
    executor: node14
    steps:
      - checkout
      - setup_deps:
          node: 14
      - run_test

  test_node12:
    executor: node12
    steps:
      - checkout
      - setup_deps:
          node: 12
      - run_test

  lint:
    executor: node16
    steps:
      - checkout
      - setup_deps:
          node: 16
      - run_lint

  coveralls:
    executor: node16
    steps:
      - checkout
      - setup_deps:
          node: 16
      - run: npm run coverage:post

workflows:
  version: 2
  build:
    jobs:
      - test_node16
      - test_node14
      - test_node12
      - lint
      - coveralls
