# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
commands:
  get_deps:
    parameters:
      node:
        type: integer
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-node<< parameters.node >>-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-node<< parameters.node >>

  save_deps:
    parameters:
      node:
        type: integer
    steps:
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-node<< parameters.node >>-{{ checksum "package.json" }}

  install_deps:
    steps:
      - run: yarn install --frozen-lockfile

  run_test:
    steps:
      - run: yarn test

  run_lint:
    steps:
      - run: yarn lint

  setup_deps:
    parameters:
      node:
        type: integer
    steps:
      - get_deps:
          node: << parameters.node >>
      - install_deps
      - save_deps:
          node: << parameters.node >>

executors:
  node10:
    docker:
      - image: circleci/node:10.16
    working_directory: ~/repo

  node8:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/repo

jobs:
  test_node10:
    executor: node10
    steps:
      - checkout
      - setup_deps:
          node: 10
      - run_test

  test_node8:
    executor: node8
    steps:
      - checkout
      - setup_deps:
          node: 8
      - run_test

  lint:
    executor: node10
    steps:
      - checkout
      - setup_deps:
          node: 10
      - run_lint

  coveralls:
    executor: node8
    steps:
      - checkout
      - setup_deps:
          node: 8
      - run: yarn coverage:post

workflows:
  version: 2
  build:
    jobs:
      - test_node12
      - test_node10
      - test_node8
      - lint
      - coveralls
