name: CI

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cmd:
          - build
          - test:coverage
          - fmt:check
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - uses: DeterminateSystems/determinate-nix-action@527f17dd63d2d60d3e5552934bc84b9a33a14d11
      - uses: cachix/cachix-action@38b082610b782e7e93e209c35fd730d399dee866
        with:
          name: gipphe
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix develop --command npm ci
      - run: nix develop --command npm run ${{ matrix.cmd }}

  results:
    name: Results
    runs-on: ubuntu-latest
    if: always()
    needs:
      - check
    steps:
      - run: |
          result="${{ needs.check.result }}"
          if [[ "$result" != "success" ]]; then
            exit 1
          fi
